mongo:
  host: localhost
  username:
  password:
  port: 27017
  databaseName: thueBDS

app:
  port: 5000

timeInterval: 1 #in minutes

rabbitmq:
  host: 103.1.239.234
  port: 5672
  username: dev
  password: brTUEaqEKwh5aYduaudg

apiHost: http://localhost:1001/
