mongo:
  host: 159.89.202.248
  username: admin
  password: abc1233VF8YLwUWjegMwyxzLv3bFu2
  port: 27017
  databaseName: bds_v1w

app:
  port: 5000

timeInterval: 1 #in minutes

rabbitmq:
  host: 103.1.239.234
  port: 5672
  username: dev
  password: brTUEaqEKwh5aYduaudg

apiHost: http://api.thuebatdongsan.com.vn
