mongo:
  host: 159.89.202.248
  username: admin
  password: abc1233VF8YLwUWjegMwyxzLv3bFu2
  port: 27017
  databaseName: bds_v1

app:
  port: 5000

timeInterval: 1 #in minutes

rabbitmq:
  host: localhost
  port: 5672
  username: admin
  password: admin123